spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JAESKAAA/spring-cloud-config
server:
  port: 8889
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JAESKAAA/spring-cloud-config
  config:
    activate:
      on-profile: local
      default-label: master
# config-server? default? 8080??? ??? ???, ????? ??? ?? ? ?? ?? ????
# ??? 8888??? ?? ??? ?????? ?? ???? ???? ???? ???? ?? ?? ??
server:
  port: 8889

---

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JAESKAAA/spring-cloud-config
#          order: 2
#        vault:
#          host: vault.cloud.com
#          port: 8200 #default port = 8200
#          scheme: http
#          order: 1
  config:
    activate:
      on-profile:
        - vault
        - git
server:
  port: 8889

---
spring:
  config:
    activate:
      on-profile: vault
server:
  port: 8889