spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JAESKAAA/spring-cloud-config-server
  config:
    activate:
      on-profile: local
      default-label: master
# config-server? default? 8080??? ??? ???, ????? ??? ?? ? ?? ?? ????
# ??? 8888??? ?? ??? ?????? ?? ???? ???? ???? ???? ?? ?? ??
server:
  port: 8889

---

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JAESKAAA/spring-cloud-config
  config:
    activate:
      on-profile: dev
#          default-label? ????? ????? ?
#          default-label: main
# config-server? default? 8080??? ??? ???, ????? ??? ?? ? ?? ?? ????
# ??? 8888??? ?? ??? ?????? ?? ???? ???? ???? ???? ?? ?? ??
server:
  port: 8889
