spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JAESKAAA/spring-cloud-config
# config-server? default? 8080??? ??? ???, ????? ??? ?? ? ?? ?? ????
# ??? 8888??? ?? ??? ?????? ?? ???? ???? ???? ???? ?? ?? ??
server:
  port: 8889